name: .NET Core Deploy to IIS

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
      
    - name: Build with dotnet
      run: dotnet build --configuration Release C:\Users\Administrateur.WINSERV-2019.000\actions-runner\_work\AdopteUnDev.API\AdopteUnDev.API\AdopteUnDev.API\AdopteUnDev.API.csproj
    
    - name: dotnet publish
      run: dotnet publish -c Release C:\Users\Administrateur.WINSERV-2019.000\actions-runner\_work\AdopteUnDev.API\AdopteUnDev.API\AdopteUnDev.API\AdopteUnDev.API.csproj -o ${{env.DOTNET_ROOT}}\AdopteUnDev.API
      
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ${{env.DOTNET_ROOT}}\AdopteUnDev.API\* C:\inetpub\wwwroot\AdopteUnDev.API -Recurse -Force
        iisreset /start
